version: '3.9'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    environment: 
      OPEN_VAGAS_DATABASE_PASSWORD: postgres
    stdin_open: true
    tty: true
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - .:/app
    command: bash -c 'rails s -b 0.0.0.0'
    depends_on:
      - db
      - redis

  db:
    image: postgres:13.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: open_vagas_development
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mailcatcher:
    image: dockage/mailcatcher
    ports:
      - 1080:1080
      - 1025:1025

  redis:
    image: redis:6.2.5
    command: redis-server
    ports:
      - "6379:6379"

  sidekiq:
    build: .
    command: bundle exec sidekiq
    depends_on:
      - db
      - redis
    volumes:
      - .:/app

volumes:
  postgresql:
  redis:
