version: '3.3'
services:
  app:
    build: .
    stdin_open: true
    tty: true
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - .:/app
    command: bash -c 'rails s -b 0.0.0.0'
    depends_on:
      - db
    environment:
      - DATABASE_HOST= "192.168.1.0"



  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: myapp_development
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  pgdata: