# PostgreSQL configuration (example for version 13)
default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV.fetch("POSTGRES_USER") { "postgres" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "postgres" } %>
  host: "192.168.1.20"

development:
  <<: *default
  database: open_vagas_development
  

test:
  <<: *default
  database: open_vagas_test

production:
  <<: *default
  database: open_vagas_production
  username: <%= ENV.fetch("OPEN_VAGAS_DATABASE_USERNAME") { "open_vagas" } %>
  password: <%= ENV.fetch("OPEN_VAGAS_DATABASE_PASSWORD") { "postgres" } %>